# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-03 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivity',
            name='has_joined',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u53c2\u52a0'),
        ),
    ]
