# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-13 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_studentactivity_has_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactivity',
            name='has_joined',
        ),
    ]
