# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-04 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='state',
            field=models.IntegerField(choices=[(0, '\u5f85\u5ba1\u6838'), (1, '\u5ba1\u6838\u901a\u8fc7')], default=0, verbose_name='\u6d3b\u52a8\u72b6\u6001'),
        ),
    ]
