# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-13 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='state',
        ),
        migrations.AddField(
            model_name='activity',
            name='has_passed',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5ba1\u6838\u901a\u8fc7'),
        ),
    ]
